### ISSUE TITLE
Codespace container fails to build for repository

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Windows#423]
## Background
GitHub Codespaces is set up with this repo so anyone can review PRs in the browser or build the toolkit via a Codespace.

## Problem
Trying to create or build a codespace on `main` results in this error:
```
-node/devContainersSpecCLI.js:614:11006)
{"outcome":"error","message":"Command failed: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/dotnet:0-8.0","description":"An error occurred setting up the container."}
devcontainer process exited with exit code 1
Failed to create container.
Error: Command failed: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/dotnet:0-8.0
Error code: 1302 (UnifiedContainersErrorFatalCreatingContainer)
Container creation failed.
```

## Solution
Unknown, needs investigation.

**Comment by Arlodotexe** [comment]
Current error message:
```
=================================================================================
2024-06-24 16:46:46.234Z: Creating container...
2024-06-24 16:46:46.285Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/CommunityToolkitWindows --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --skip-post-create --config "/var/lib/docker/codespacemount/workspace/CommunityToolkitWindows/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
2024-06-24 16:46:46.535Z: @devcontainers/cli 0.56.1. Node.js v18.20.3. linux 6.5.0-1021-azure x64.
2024-06-24 16:46:46.992Z: Error: Command failed: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/dotnet:0-8.0
2024-06-24 16:46:47.002Z: {"outcome":"error","message":"Command failed: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/dotnet:0-8.0","description":"An error occurred setting up the container."}
2024-06-24 16:46:47.008Z:     at O$ (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:464:1253)
2024-06-24 16:46:47.023Z:     at iK (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:464:997)
2024-06-24 16:46:47.026Z:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-24 16:46:47.029Z:     at async gAA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:481:3660)
2024-06-24 16:46:47.035Z:     at async BC (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:481:4775)
2024-06-24 16:46:47.146Z:     at async xeA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:614:11265)
2024-06-24 16:46:47.150Z:     at async UeA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:614:11006)
2024-06-24 16:46:47.157Z: devcontainer process exited with exit code 1
```

**Comment by Arlodotexe** [comment]
Tried again, but the creation log still doesn't provide enough information to find out why it won't build:
```
2024-08-01 18:01:00.814Z: Host information
2024-08-01 18:01:00.824Z: ----------------
2024-08-01 18:01:00.825Z: OS: Ubuntu 22.04.4 LTS (stable release)
2024-08-01 18:01:00.825Z: Image details: https://github.com/github/codespaces-host-images/blob/main/README.md
2024-08-01 18:01:00.825Z: ----------------

=================================================================================
2024-08-01 18:01:00.825Z: Configuration starting...
2024-08-01 18:01:00.837Z: Cloning...

=================================================================================
2024-08-01 18:01:00.913Z: Creating container...
2024-08-01 18:01:01.054Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/Windows --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --skip-post-create --expect-existing-container --config "/var/lib/docker/codespacemount/workspace/Windows/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
2024-08-01 18:01:01.292Z: @devcontainers/cli 0.56.1. Node.js v18.20.3. linux 6.5.0-1022-azure x64.
2024-08-01 18:01:01.438Z: $ docker start b4e1356d9c26f5475972dda9d717cc593dab411915285de7427b03077f117ee0
2024-08-01 18:01:01.814Z: b4e1356d9c26f5475972dda9d717cc593dab411915285de7427b03077f117ee0

2024-08-01 18:01:01.818Z: Stop: Run: docker start b4e1356d9c26f5475972dda9d717cc593dab411915285de7427b03077f117ee0
2024-08-01 18:01:01.990Z: Outcome: success User: vscode WorkspaceFolder: /workspaces/Windows
2024-08-01 18:01:02.006Z: devcontainer process exited with exit code 0

=================================================================================
2024-08-01 18:01:02.353Z: Running blocking commands...
2024-08-01 18:01:02.456Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/Windows --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --expect-existing-container --config "/var/lib/docker/codespacemount/workspace/Windows/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
2024-08-01 18:01:02.639Z: @devcontainers/cli 0.56.1. Node.js v18.20.3. linux 6.5.0-1022-azure x64.
2024-08-01 18:01:02.897Z: Outcome: success User: vscode WorkspaceFolder: /workspaces/Windows
2024-08-01 18:01:02.904Z: devcontainer process exited with exit code 0

=================================================================================
2024-08-01 18:01:02.955Z: Configuring codespace...

=================================================================================
2024-08-01 18:01:03.227Z: Running commands...
2024-08-01 18:01:03.227Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/Windows --expect-existing-container --skip-post-attach --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --config "/var/lib/docker/codespacemount/workspace/Windows/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
2024-08-01 18:01:03.635Z: @devcontainers/cli 0.56.1. Node.js v18.20.3. linux 6.5.0-1022-azure x64.
2024-08-01 18:01:03.922Z: Outcome: success User: vscode WorkspaceFolder: /workspaces/Windows
2024-08-01 18:01:03.928Z: devcontainer process exited with exit code 0

=================================================================================
2024-08-01 18:01:04.427Z: Finished configuring codespace.
```
