### ISSUE TITLE
Shadows overview sample in gallery crashes under Windows App SDK

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Windows#512]
### Describe the bug

When running the gallery with the Wasdk head on the latest `main` commit, the AttachedCardShadow sample will crash the app:
![image](https://github.com/user-attachments/assets/5bc2fb0d-881f-4cd7-93ae-d813d61d5c31)

Exception message:
> Specified cast is not valid.

Stack trace:
```
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.MeasureOverride(IObjectReference _obj, Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Size availableSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)
```

This behavior is not present when running the gallery under UWP.

### Steps to reproduce

```text
1. Clone the repo
2. Generate the gallery solution, include the Media component and the wasdk multitarget/head.
3. Build and deploy the wasdk gallery 
4. Navigate to the 'Shadows overview' sample page and observe crash.
```

### Expected behavior

No crash

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by Arlodotexe** [comment]
This error only throws when AoT is enabled. Running without AoT works as expected:

![Image](https://github.com/user-attachments/assets/179020d2-8ebe-4c87-af70-caee8e06b422)

Also worth noting that this document doesn't have any embedded samples in it. This means might be an issue with the `MarkdownTextBlock` being used by the gallery.

**Comment by Arlodotexe** [comment]
We're still using 7.1.2 for the Markdown renderer in the Gallery: 
- [tooling/ProjectHeads/App.Head.Uwp.Dependencies.props#L5](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/blob/9375f96fafe362e1a549ecd157cbc3f7ba20ecaf/ProjectHeads/App.Head.Uwp.Dependencies.props#L5)
- [tooling/ProjectHeads/App.Head.WinAppSdk.Dependencies.props#L5](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/blob/9375f96fafe362e1a549ecd157cbc3f7ba20ecaf/ProjectHeads/App.Head.WinAppSdk.Dependencies.props#L5).

These will need to be updated to the latest version of [`MarkdownTextBlock`](https://github.com/CommunityToolkit/Labs-Windows/tree/7b163ce0ea619cb712ed2ab3f0c6aeb0c9d771d9/components/MarkdownTextBlock) in Labs.

**Comment by Arlodotexe** [comment]
Looking through the new Markdig-based Markdown control, I'm not seeing any obvious way to handle clicked links in the consuming application. 

I see the library has an [`AutoLinkParser`](https://github.com/xoofx/markdig/blob/master/src/Markdig/Extensions/AutoLinks/AutoLinkParser.cs#L16) that takes an [`AutoLinkOptions.OpenInNewWindow`](https://github.com/xoofx/markdig/blob/master/src/Markdig/Extensions/AutoLinks/AutoLinkOptions.cs#L19), but [AutoLink](https://github.com/xoofx/markdig/blob/master/src/Markdig.Tests/Specs/AutoLinks.md) seems to be centered around detecting and making raw links clickable in the renderer. It's not clear where or how link clicks are handled from code-behind.

Looking at another UI project that uses Mardig, [markdig.wpf](https://github.com/Kryptos-FR/markdig.wpf/), we find that their sample app is routing "hyperlink clicks" [through FrameworkElement CommandBindings](https://github.com/Kryptos-FR/markdig.wpf/blob/3dced7721c9245b618ce62732d4e078b38d22a89/src/Markdig.Wpf.SampleApp/MainWindow.xaml#L10). Digging further, they've connected this binding through a `Hyperlink` object that is passed to a custom wpf-based [`LinkInlineRenderer`](https://github.com/Kryptos-FR/markdig.wpf/blob/3dced7721c9245b618ce62732d4e078b38d22a89/src/Markdig.Wpf/Renderers/Wpf/Inlines/LinkInlineRenderer.cs#L54-L60). 

We'll need to create a similar custom link renderer in the `MarkdownTextBlock` control offered in Labs before we can move forward with this ticket.
